name: Publish

on: 
  release: 
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Node v14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm install
        name: Install Node dependencies
      
      - run: (cd ./utils && sh ./build.sh)
        name: Build opencv-wasm

      - run: (cd utils && node generateCvProps.js)
        name: generateCvProps
      
      - run: (cd ./build_wasm_test/bin && npm install)
        name: Install Node dependencies for test provided by OpenCV

      - run: (cd ./build_wasm_test/bin && node tests.js)
        name: Run test provided by OpenCV
      
      - uses: JS-DevTools/npm-publish@v1
        with:
          access: "public"
          token: ${{ secrets.NPM_ACCESS_TOKEN }}

      - uses: JS-DevTools/npm-publish@v1
        with:
          access: "public"
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
